SELECT UA. ID, UA.FIRST_NAME, UA.LAST_NAME, C.ID, C.CUSTOMER_NAME, COUNT (*) FROM CONTACT CON
INNER JOIN CUSTOMER C ON C.ID = CON.CUSTOMER_ID

INNER JOIN USER_ACCOUNT UA ON UA.ID CON.USER_ACCOUNT_ID

 GROUP BY UA.ID, UA.FIRST NAME, UA.LAST NAME, C.ID, C.CUSTOMER_NAME

HAVING COUNT(*)>1

ORDER BY UA. ID;
