SELECT C.COUNTRY_NAME, COUNT(*), AVG(I.TOTAL_PRICE) FROM COUNTRY C
JOIN CITY CI ON C.ID = CI.COUNTRY_ID
JOIN CUSTOMER CR ON CI.ID = CR.CITY_ID
JOIN INVOICE I ON CR.ID = I.CUSTOMER_ID
GROUP BY C.COUNTRY_NAME
HAVING AVG(I.TOTAL_PRICE) > (SELECT AVG(TOTAL_PRICE) FROM INVOICE);
